<?php
/**
 * BackofficeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Morpheus
 *
 * Morpheus is a microservice for sending SMS to passenger and drivers.
 *
 * OpenAPI spec version: 3.5.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * BackofficeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BackofficeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiPrioritiesGet
     *
     * Current provider's priorities list..
     *
     */
    public function testApiPrioritiesGet()
    {
    }

    /**
     * Test case for apiPrioritiesPost
     *
     * Updates provider's priorities list..
     *
     */
    public function testApiPrioritiesPost()
    {
    }

    /**
     * Test case for apiTemplateNameDelete
     *
     * Deletes the message template specified by {name}..
     *
     */
    public function testApiTemplateNameDelete()
    {
    }

    /**
     * Test case for apiTemplateNameGet
     *
     * Returns the message template specified by {name}..
     *
     */
    public function testApiTemplateNameGet()
    {
    }

    /**
     * Test case for apiTemplatePost
     *
     * Creates a message template..
     *
     */
    public function testApiTemplatePost()
    {
    }

    /**
     * Test case for apiTemplatePut
     *
     * Updates a message template..
     *
     */
    public function testApiTemplatePut()
    {
    }

    /**
     * Test case for apiTemplatesMediaGet
     *
     * Returns the message templates of tyepe {name}..
     *
     */
    public function testApiTemplatesMediaGet()
    {
    }

    /**
     * Test case for apiTokenBanPost
     *
     * Ban a token..
     *
     */
    public function testApiTokenBanPost()
    {
    }

    /**
     * Test case for apiTokenUnbanPost
     *
     * Unban a token..
     *
     */
    public function testApiTokenUnbanPost()
    {
    }

    /**
     * Test case for providers
     *
     * returns all implemented providers.
     *
     */
    public function testProviders()
    {
    }
}
